# Generated by Django 5.1.6 on 2025-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_remove_customuser_distance_manual_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='distance_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
